dijkstra:
  search:
    dir: /Users/arturhebda/Desktop
    file: Dijkstra.debug

  result:
    path: /Users/arturhebda/Desktop/path.xml

osm:
  source:
    path: /Users/arturhebda/Downloads/map.osm

  image:
    path:
      absolute: <%= Rails.root.join('public', 'images', 'map.svg') %>
      relative: <%= File.join('/', 'images', 'map.svg') %> # relative to public (for html)

    width: 1050
    height: 797

  bounds:
    min:
      latitude: 50.05861
      longitude: 19.9307

    max:
      latitude: 50.06633
      longitude: 19.94654
