--- 
dijkstra: 
  search: 
    dir: /Users/arturhebda/Desktop
    file: Dijkstra.debug
  result: 
    path: /Users/arturhebda/Desktop/path.xml
osm: 
  source: 
    path: /Users/arturhebda/Downloads/map.osm
  image: 
    path: 
      absolute: <%= Rails.root.join('public', 'images', 'map.svg') %>
      relative: <%= File.join('/', 'images', 'map.svg') %>
    dimensions: 
      width: 1049
      height: 858
  bounds: 
    min: 
      latitude: 50.05831
      longitude: 19.9307
    max: 
      latitude: 50.06663
      longitude: 19.94654
